editar /etc/apt/sources.list y descompentar linea de cdrom
apt-get update
apt-get install -y openssh-server build-essential linux-headers-server

meter cd de drivers de la asus y copiar directorio entero

cp -R /mnt/cdrom/LinuxDrivers/Lan/AR8121-linux-ver1.0.0.7/ /usr/src/atheros2/
cd /usr/src/atheros2/
KBUILD_NOPEDANTIC=1 make install
insmod /lib/modules/2.6.24-19-server/kernel/drivers/net/atl1e/atl1e.ko

echo "atl1e" >> /etc/modules

echo 192.168.0.1 > /etc/resolv.conf

a /etc/network/interfaces

auto eth0
iface eth0 inet static
address 192.168.0.9
gateway 192.168.0.253
netmask 255.255.255.0
network 192.168.0.0
broadcast 192.168.0.255

actualizar /etc/apt/sources.list

apt-get dist-upgrade

apt-get install ia32-libs xinetd
cd /usr/src
wget http://download3.vmware.com/software/vmserver/VMware-server-1.0.7-108231.tar.gz

apt-get install ddclient

/etc/ddclient.conf
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

pid=/var/run/ddclient.pid
protocol=dyndns2
server=members.dyndns.org
login=s1lence
password=klp008
gmhq.game-host.org
use=web, web=checkip.dyndns.org:8245/, web-skip='Current IP Address: '

#instalar o copiar las vms necesarias

echo "Port 62331" >> /etc/ssh/sshd_config
/etc/init.d/sshd restart

# wget http://www.atlassian.com/software/bamboo/downloads/binary/atlassian-bamboo-2.1.1-standalone.tar.gz

# postgresql
# bamboo
apt-get install sun-java6-bin sun-java6-jdk sun-java6-jre
# descargar ultima version

echo "bamboo.home=/home/slnc/bamboo" >  /usr/local/hosting/Bamboo/webapp/WEB-INF/classes/bamboo-init.properties

scp ./webapp/WEB-INF/lib/postgresql-8.2-504.jdbc3.jar root@balrog:/usr/local/hosting/Bamboo/webapp/WEB-INF/lib/


# dnscache
apt-get install dnsmasq



# xcpine
instalar emule y activar webui
instalar utorrent y activar webui

apt-get install libtidy-ruby libtidy-ruby1.8

apt-get install libxml2 libxml2-dev swig #subversion
