source :rubygems

gem "aasm"
gem "ai4r"
gem "daemons"
gem "deadlock_retry"
gem "delayed_job", "~> 3.0.1"
gem "delayed_job_active_record"
gem "exception_notification"
gem "feedtools"
gem "feedvalidator"
gem "geoip"
gem "gruff"
gem "jquery-rails", ">= 1.0.12"
gem "log4r"
gem "newrelic_rpm"
gem "passenger"
gem "pg"
gem "rails", "3.2.1"
gem "rails_autolink"
gem "rmagick", :require => "RMagick"
gem "tidy"
gem "will_paginate", "~> 3.0"
