source "http://rubygems.org"

gem "ai4r"
gem "blackbook"
gem "capistrano"
gem "ci_reporter"
gem "clusterer"
gem "feedtools"
gem "feedvalidator"
gem "geoip"
gem "gruff"
gem "nokogiri"
gem "rails", "~> 2.3.5"
gem "rcov"
gem "rmagick"
gem "rubystats"
gem "ruby-pg"
gem "tidy"
