insert into content_types(name) VALUES('news');
insert into content_types(name) VALUES('offtopic');
insert into content_types(name) VALUES('article');
insert into content_types(name) VALUES('image');
insert into content_types(name) VALUES('download');
insert into content_types(name) VALUES('forumtopic');
insert into content_types(name) VALUES('poll');
insert into content_types(name) values('event');
insert into content_types(name) values('eventsnews');
