-- CHEATSHEET FOR DOING DUMPS
-- For specific tables:
-- pg_dump -Oxa --column-inserts -t terms gamersmafia > terms.sql
--
-- For specific rows:
-- CREATE temptable as SELECT ...
-- pg_dump -Oxa --column-inserts -t temptable gamersmafia > temptable.sql

TRUNCATE comments_valorations_types CASCADE;
TRUNCATE content_types CASCADE;
TRUNCATE games CASCADE;
TRUNCATE global_vars;
TRUNCATE terms CASCADE;
TRUNCATE users CASCADE;

INSERT INTO global_vars (id, online_anonymous, online_registered, svn_revision, ads_slots_updated_on, gmtv_channels_updated_on, max_cache_valorations_weights_on_self_comments) VALUES (1, 363, 73, '68d5428', '2011-07-30 18:17:39.727069', '2010-01-10 21:44:56.169444', 242403.0);

INSERT INTO content_types (id, name) VALUES (1, 'News');
INSERT INTO content_types (id, name) VALUES (15, 'Bet');
INSERT INTO content_types (id, name) VALUES (4, 'Image');
INSERT INTO content_types (id, name) VALUES (5, 'Download');
INSERT INTO content_types (id, name) VALUES (23, 'Demo');
INSERT INTO content_types (id, name) VALUES (7, 'Poll');
INSERT INTO content_types (id, name) VALUES (8, 'Event');
INSERT INTO content_types (id, name) VALUES (10, 'Tutorial');
INSERT INTO content_types (id, name) VALUES (11, 'Interview');
INSERT INTO content_types (id, name) VALUES (12, 'Column');
INSERT INTO content_types (id, name) VALUES (13, 'Review');
INSERT INTO content_types (id, name) VALUES (14, 'Funthing');
INSERT INTO content_types (id, name) VALUES (17, 'Blogentry');
INSERT INTO content_types (id, name) VALUES (6, 'Topic');
INSERT INTO content_types (id, name) VALUES (9, 'Coverage');
INSERT INTO content_types (id, name) VALUES (24, 'Question');
INSERT INTO content_types (id, name) VALUES (25, 'RecruitmentAd');


INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (95, 'Gamersmafia', 'gm', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, 35966, 95, NULL);

INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (4988, 'GmVersion', 'gmversion', '', NULL, NULL, NULL, NULL, NULL, 89, NULL, -18199, 4988, NULL);

INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (97, 'Bazar', 'bazar', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, -16394, 97, NULL);

INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (908, 'Arena', 'arena', '', NULL, NULL, NULL, NULL, NULL, 0, NULL, -16443, 908, NULL);

INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (1559, 'Babes', 'babes', '', 97, NULL, NULL, NULL, NULL, 0, NULL, -16351, 97, 'ImagesCategory');

INSERT INTO terms (id, name, slug, description, parent_id, game_id, platform_id, bazar_district_id, clan_id, contents_count, last_updated_item_id, comments_count, root_id, taxonomy)
  VALUES (1560, 'Dudes', 'dudes', '', 97, NULL, NULL, NULL, NULL, 0, NULL, -16502, 97, 'ImagesCategory');

INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (474, 'General', 'general_23', 'DownloadsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2396, 'Party Larga', 'party-larga_2', 'EventsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2397, 'Party Corta', 'party-corta_2', 'EventsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (1570, 'Wallpapers GM', 'wallpapers-gm', 'ImagesCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2170, 'Partys', 'partys_4', 'NewsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2171, 'Competiciones', 'competiciones_36', 'NewsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (869, 'General', 'general_86', 'TopicsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (871, 'Sugerencias', 'sugerencias', 'TopicsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2262, 'General', 'general_264', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2282, 'Programas de Comunicacion', 'programas-de-comunicacion_1', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2283, 'Pc//Sistema Operativo', 'pc-sistema-operativo', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2284, 'Punkbuster', 'punkbuster_13', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2285, 'Conceptos', 'conceptos', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2286, 'Clanbase', 'clanbase_7', 'TutorialsCategory', 95, 95);
INSERT INTO terms (id, name, slug, taxonomy, parent_id, root_id) VALUES (2287, 'Tutoriales para videofrags', 'tutoriales-para-videofrags', 'TutorialsCategory', 95, 95);

INSERT INTO comments_valorations_types (id, name, direction) VALUES (1, 'Normal', 0);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (2, 'Divertido', 1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (3, 'Informativo', 1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (4, 'Profundo', 1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (5, 'Flame', -1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (6, 'Redundante', -1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (7, 'Irrelevante', -1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (8, 'Interesante', 1);
INSERT INTO comments_valorations_types (id, name, direction) VALUES (9, 'Spam', -1);

INSERT INTO games (id, name, code, has_guids, guid_format) VALUES (1, 'Unreal Tournament', 'ut', false, '');
insert into terms(id, root_id, name, slug, game_id) VALUES(1, 1, 'Unreal Tournament', 'ut', 1);

INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (26740, 'nagato', '6756261aa0fbca41602bb3e68fd1be83', 'e72c5d921b364aa275daecf7815eef40', 'nagato@gamersmafia.com', NULL, '10.211.55.2', '2007-01-01 03:37:46.550389', '2012-02-01 12:25:10.678073', 'Nagato', '', NULL, '2010-04-14 01:15:14.166181', NULL, NULL, NULL, 'Desconocida', '', 1, '', NULL, '1982-03-07', 475, '', 115, 'storage/users/0026/740_nagato.jpg', '', '', '', '', '', '', '', '', '', '', 'Hola, trabajo para Gamersmafia. Soy la encargada de comunicar distintos tipos de mensajes a los usuarios.

¡Encantada de conocerte!', false, 7, NULL, 80, false, false, false, false, '', 968, 66771, '2012-02-01 12:25:10.623457', true, NULL, 141.00, '2010-04-14 01:13:51.743674', 0, NULL, -1, NULL, NULL, false, false, true, 28, NULL, false, NULL, NULL, NULL, false, true, true, NULL, false, 2, false, NULL, '1548943521', 2, 0.92, false, NULL, NULL, true, NULL, NULL, 0.48878867365419898, true, 0, 1669, 1084, 101, 5, false, 584.438, 1);

INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (43237, 'MrAchmed', '6756261aa0fbca41602bb3e68fd1be83', '19428c5ae4692637041f511f61024bcf', 'mrachmed@gamersmafia.com', NULL, '10.211.55.2', '2008-09-11 00:00:00', '2012-02-18 21:56:44.025638', '', '', NULL, '2010-04-11 01:31:29.867577', NULL, NULL, NULL, '', '', 0, '', NULL, '1969-09-19', 10825, '', 3, 'storage/users/0043/237_achmed_full.jpg', '', '', '', '', '', '', '', '', '', '', 'Soy el jefe del departamento de inteligencia.

Me gustan mucho las vírgenes. Si eres virgen mándame un mensaje privado.', false, 48, NULL, 50, false, false, false, false, '', 20, 58622, '2012-02-12 13:18:58.397987', true, NULL, 2150.00, '2010-04-11 01:31:28.147712', 0, NULL, -1, NULL, NULL, false, true, true, 27, '                ', false, '', '', '', false, true, true, NULL, false, true, '000001', 2, false, '2008-09-19 19:54:50.924515', '1309260655', 2, 0.77, true, 'Silence, I kill you!', true, true, 0.052730087190866498, false, 35, 230, 1269, 199, 2, false, 2919.34, 1);

INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (23323, 'MrAlariko', '6756261aa0fbca41602bb3e68fd1be83', '0dfb79b287001a629e59e430fb7c3308', 'mralariko@gamersmafia.com', NULL, '10.211.55.2', '2006-07-15 00:37:12', '2011-08-28 15:03:05.627388', NULL, NULL, NULL, '2009-11-25 00:01:06.396623', NULL, '2006-07-15 00:38:03', NULL, NULL, NULL, NULL, NULL, NULL, '1999-11-30', 5, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 1, NULL, 0, false, false, false, false, NULL, 28, 56153, '2011-08-28 14:46:18.391105', true, NULL, 1.00, '2009-11-25 00:01:04.340127', 0, NULL, -1, NULL, NULL, false, false, true, 3, NULL, false, NULL, NULL, NULL, true, true, true, NULL, false, 2, false, NULL, '951687063', 3, 0.52, false, NULL, NULL, true, NULL, '', 0.105776853393763, false, 0, 12867, 21953, 285, 1, false, 422.759, 1);
INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (23767, 'MrMan', '6756261aa0fbca41602bb3e68fd1be83', '583299d3806004b1474ea931ef79e896', 'mrman@gamersmafia.com', NULL, '10.211.55.2', '2006-08-07 20:59:25', '2012-02-18 21:56:57.806882', 'MrMan', '', NULL, '2010-05-26 10:53:28.891051', NULL, NULL, NULL, '', '', 0, '', NULL, '1952-09-25', 44775, '', NULL, 'storage/users/0023/767_mrmanbig.jpg', '', '', '', '', '', '', '', '', '', '', 'Podéis llamarme Man, MrMan.', false, 1171, NULL, 11825, false, false, false, false, '', 81, 69918, '2012-01-21 19:20:24.197941', true, NULL, 14332.00, '2012-02-14 04:50:59.616335', 0, NULL, -1, NULL, NULL, false, false, true, 15, '                ', false, '', '', '', true, true, true, NULL, false, 2, false, '2008-10-02 19:50:10.337013', '1108469218', 2, 0.34, false, NULL, NULL, true, NULL, '01', 0.14540581032633801, false, 35, 37, 134, 698, 0, false, 1493.97, 1);
INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (23319, 'MrCheater', '6756261aa0fbca41602bb3e68fd1be83', '8a7cb4d90d12413796936947ac3d21bd', 'mrcheater@gamersmafia.com', NULL, '10.211.55.2', '2005-11-15 00:00:00', '2012-02-17 21:10:37.936941', '', '', NULL, '2010-03-25 21:07:56.816035', NULL, '2006-12-10 16:44:02.571759', NULL, 'Gamersmafia', 'http://gamersmafia.com/miembros/mrcheater', 0, '', NULL, '1994-03-07', 4020, '', NULL, '/storage/users/23/yo.jpg', '', '', '', '', '', '', '', '', '', '', 'No puedes asegurarlo.', false, 24, NULL, 15, false, false, false, false, '', 215, 57689, '2012-02-17 21:10:37.903231', true, NULL, 729.00, '2010-03-25 21:08:47.886284', 0, NULL, -1, NULL, NULL, false, false, true, 6, NULL, false, NULL, NULL, NULL, true, true, true, NULL, false, 2, false, NULL, '738291394', 2, 0.65, true, NULL, true, true, NULL, NULL, 0.46858671214431502, false, 0, 508, 1684, 81, 6, false, 1461.43, 1);
INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (23322, 'MrGod', '6756261aa0fbca41602bb3e68fd1be83', 'f06c1a28cd407ccec905b699a857c834', 'mrgod@gamersmafia.com', NULL, '10.211.55.2', '2005-11-15 00:00:00', '2012-01-22 20:20:19.908215', 'MrGod', '', NULL, '2010-02-02 23:27:46.671873', NULL, NULL, NULL, '', 'http://gamersmafia.com/miembros/mrgod', 0, '', NULL, '1939-09-01', 35, '', NULL, '/storage/users/23/MrGod.jpg', 'No, gracias, prefiero otro tipo de carne', 'Superior', 'No, me lavo los dientes todos los días', 'Nunca olvido una cara', 'Y también la cabeza', 'Me salgo', 'Envolvente, no lo dudes..', 'Son los vecinos los que se preocupan de no molestarme', 'soy dios, YO soy el monitor', 'La necesaria para poder estar en todas partes a la vez', 'Creo que no necesito presentación.

Oh y además Chuck Norris no me llega ni a la suela de los zapatos.', false, 6, NULL, 0, true, false, true, true, '', 8, 58391, '2011-12-22 01:24:28.177561', true, NULL, 11.00, '2010-02-02 23:28:02.101345', 0, NULL, -1, NULL, NULL, false, false, true, 4, NULL, false, NULL, NULL, NULL, true, true, true, NULL, false, 2, false, NULL, '125736784', 5, 0.58, false, NULL, NULL, true, NULL, NULL, 0.37922866409644501, false, 0, 6537, 21952, 698, 0, false, 522.208, 1);

-- unnamed
INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (1, 'unnamed', '6756261aa0fbca41602bb3e68fd1be83', 'ed73c0cffec07a74b180bc395e2922f5', 'unnamed@example.com', NULL, '10.211.55.2', '2012-02-05 12:01:33.913929', '2012-02-18 16:18:31.885697', '', '', NULL, '2012-02-18 16:17:51.946291', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 45, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, true, 1, NULL, 0, true, true, true, true, NULL, 0, NULL, NULL, true, NULL, 1000.00, '2012-02-05 13:52:47.172554', 0, NULL, -1, NULL, NULL, false, false, false, 0, NULL, false, NULL, NULL, NULL, true, true, true, 5, false, 1, false, NULL, '1509458161', 1, 1.00, false, NULL, NULL, false, NULL, NULL, NULL, false, 0, NULL, NULL, NULL, NULL, false, 0.0, 1);
INSERT INTO users (id, login, password, validkey, email, newemail, ipaddr, created_on, updated_at, firstname, lastname, image, lastseen_on, faction_id, faction_last_changed_on, avatar_id, city, homepage, sex, msn, icq, birthday, cache_karma_points, irc, country_id, photo, hw_mouse, hw_processor, hw_motherboard, hw_ram, hw_hdd, hw_graphiccard, hw_soundcard, hw_headphones, hw_monitor, hw_connection, description, is_superadmin, comments_count, referer_user_id, cache_faith_points, notifications_global, notifications_newmessages, notifications_newregistrations, notifications_trackerupdates, xfire, cache_unread_messages, resurrected_by_user_id, resurrection_started_on, using_tracker, secret, cash, lastcommented_on, global_bans, last_clan_id, antiflood_level, last_competition_id, competition_roster, enable_competition_indicator, is_hq, enable_profile_signatures, profile_signatures_count, wii_code, email_public, gamertag, googletalk, yahoo_im, notifications_newprofilesignature, tracker_autodelete_old_contents, comment_adds_to_tracker_enabled, cache_remaining_rating_slots, has_seen_tour, state, cache_is_faction_leader, profile_last_updated_on, visitor_id, comments_valorations_type_id, comments_valorations_strength, enable_comments_sig, comments_sig, comment_show_sigs, has_new_friend_requests, emblems_mask, random_id, is_staff, pending_alerts, ranking_karma_pos, ranking_faith_pos, ranking_popularity_pos, cache_popularity, login_is_ne_unfriendly, cache_valorations_weights_on_self_comments, default_comments_valorations_weight) VALUES (10000, 'jabba', '6756261aa0fbca41602bb3e68fd1be83', '0dfb79b287001a629e59e430fb7c3308', 'jabba@gamersmafia.com', NULL, '10.211.55.3', '2006-07-15 00:37:12', '2011-08-28 15:03:05.627388', NULL, NULL, NULL, '2009-11-25 00:01:06.396623', NULL, '2006-07-15 00:38:03', NULL, NULL, NULL, NULL, NULL, NULL, '1999-11-30', 5, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, 1, NULL, 0, false, false, false, false, NULL, 28, 56153, '2011-08-28 14:46:18.391105', true, NULL, 1.00, '2009-11-25 00:01:04.340127', 0, NULL, -1, NULL, NULL, false, false, true, 3, NULL, false, NULL, NULL, NULL, true, true, true, NULL, false, 2, false, NULL, '951687063', 3, 0.52, false, NULL, NULL, true, NULL, '', 0.105776853393763, false, 0, 12867, 21953, 285, 1, false, 422.759, 1);

-- ClansGroupsTypes
INSERT INTO clans_groups_types(name) VALUES('clanleaders');
INSERT INTO clans_groups_types(name) VALUES('members');

INSERT INTO games_maps (id, name, game_id, download_id, screenshot) VALUES (1, 'DM-Deck16', 1, NULL, NULL);

-- UserSkills
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'unnamed'), 'Webmaster');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'jabba'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'MrAlariko'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'MrAchmed'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'MrCheater'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'MrGod'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'MrMan'), 'Bot');
INSERT INTO users_skills (user_id, role) VALUES ((SELECT id FROM users WHERE login = 'nagato'), 'Bot');
