#!/usr/bin/env ruby

unless ARGV.size == 1
	$stderr.puts "USAGE: #{0} [environment]"
	exit 1
end

RAILS_ENV = ARGV.first
require File.dirname(__FILE__) + '/../config/environment'

Delayed::Worker.new.start