class AddColumnsToContents < ActiveRecord::Migration
  def change
    execute "alter table contents add column description text;"
    execute "alter table contents add column main text;"
    execute "alter table contents add column hits_registered int not null default 0;"
    execute "alter table contents add column hits_anonymous int not null default 0;"
    execute "alter table contents add column cache_rating smallint;"
    execute "alter table contents add column cache_rated_times smallint;"
    execute "alter table contents add column cache_comments_count smallint not null default 0;"
    execute "alter table contents add column log varchar;"
    execute "alter table contents add column cache_weighted_rank numeric(10, 2);"
    execute "alter table contents add column type varchar;"
    execute "update contents set type = (SELECT name from content_types WHERE id = content_type_id);"
    execute "alter table contents alter column type set not null"
    execute "alter table contents drop content_type_id;"
    execute "alter table contents drop is_public;"
    execute "alter table contents rename column name to title;"
    execute "create index contents_type on contents(type);"

    execute "alter table contents add column cancelled bool default 'f';"
    execute "alter table contents add column closes_on timestamp;"
    execute "alter table contents add column forfeit bool default 'f';"
    execute "alter table contents add column tie bool default 'f';"
    execute "alter table contents add column total_ammount numeric(14, 2);"
    execute "alter table contents add column winning_bets_option_id int references bets_options;"
    execute "alter table contents add column file_hash_md5 varchar;"
    execute "alter table contents add column file varchar;"
    execute "alter table contents add column downloaded_times int;"
    execute "alter table contents add column essential bool not null default 'f';"
    execute "alter table contents add column sticky bool;"
    execute "alter table contents add column moved_on timestamp;"
    execute "alter table contents add column starts_on timestamp;"
    execute "alter table contents add column ends_on timestamp;"
    execute "alter table contents add column polls_votes_count int not null default 0;"
    execute "alter table contents add column event_id int references events;"
    execute "alter table contents add column home_image varchar;"
    execute "alter table contents add column entity1_local_id int;"
    execute "alter table contents add column entity2_local_id int;"
    execute "alter table contents add column entity1_external varchar;"
    execute "alter table contents add column entity2_external varchar;"
    execute "alter table contents add column games_map_id int references games_maps;"
    execute "alter table contents add column pov_type smallint;"
    execute "alter table contents add column pov_entity smallint;"
    execute "alter table contents add column file_size bigint;"
    execute "alter table contents add column games_mode_id int references games_modes;"
    execute "alter table contents add column games_version_id int references games_versions;"
    execute "alter table contents add column demotype int;"
    execute "alter table contents add column played_on date;"
    execute "alter table contents add column ammount numeric(10, 2);"
    execute "alter table contents add column answered_on timestamp;"
    execute "alter table contents add column answer_selected_by_user_id int references users;"
    execute "alter table contents add column country_id int;"
    execute "alter table contents add column levels varchar;"
    execute "alter table contents add column clan_id int references clans;"
  end
end
